
tokens = [
	("mirac_token_type_keyword_lnot", "!"),
	("mirac_token_type_keyword_mod", "%"),
	("mirac_token_type_keyword_band", "&"),
	("mirac_token_type_keyword_land", "&&"),
	("mirac_token_type_keyword_mul", "*"),
	("mirac_token_type_keyword_add", "+"),
	("mirac_token_type_keyword_sub", "-"),
	("mirac_token_type_keyword_div", "/"),
	("mirac_token_type_keyword_as", "as"),
	("mirac_token_type_keyword_bnot", "~"),
	("mirac_token_type_keyword_bor", "|"),
	("mirac_token_type_keyword_bxor", "^"),
	("mirac_token_type_keyword_do", "do"),
	("mirac_token_type_keyword_drop", "drop"),
	("mirac_token_type_keyword_dup", "dup"),
	("mirac_token_type_keyword_elif", "elif"),
	("mirac_token_type_keyword_else", "else"),
	("mirac_token_type_keyword_end", "end"),
	("mirac_token_type_keyword_eq", "=="),
	("mirac_token_type_keyword_f32", "f32"),
	("mirac_token_type_keyword_f64", "f64"),
	("mirac_token_type_keyword_func", "func"),
	("mirac_token_type_keyword_gt", ">"),
	("mirac_token_type_keyword_gteq", ">="),
	("mirac_token_type_keyword_i08", "i08"),
	("mirac_token_type_keyword_i16", "i16"),
	("mirac_token_type_keyword_i32", "i32"),
	("mirac_token_type_keyword_i64", "i64"),
	("mirac_token_type_keyword_if", "if"),
	("mirac_token_type_keyword_inl", "inl"),
	("mirac_token_type_keyword_ld08", "ld08"),
	("mirac_token_type_keyword_ld16", "ld16"),
	("mirac_token_type_keyword_ld32", "ld32"),
	("mirac_token_type_keyword_ld64", "ld64"),
	("mirac_token_type_keyword_let", "let"),
	("mirac_token_type_keyword_loop", "loop"),
	("mirac_token_type_keyword_lor", "||"),
	("mirac_token_type_keyword_ls", "<"),
	("mirac_token_type_keyword_lseq", "<="),
	("mirac_token_type_keyword_lxor", "^^"),
	("mirac_token_type_keyword_mem", "mem"),
	("mirac_token_type_keyword_neq", "!="),
	("mirac_token_type_keyword_over", "over"),
	("mirac_token_type_keyword_ptr", "ptr"),
	("mirac_token_type_keyword_reg", "reg"),
	("mirac_token_type_keyword_req", "req"),
	("mirac_token_type_keyword_ret", "ret"),
	("mirac_token_type_keyword_rot", "rot"),
	("mirac_token_type_keyword_shl", "<<"),
	("mirac_token_type_keyword_shr", ">>"),
	("mirac_token_type_keyword_sys1", "sys1"),
	("mirac_token_type_keyword_sys2", "sys2"),
	("mirac_token_type_keyword_sys3", "sys3"),
	("mirac_token_type_keyword_sys4", "sys4"),
	("mirac_token_type_keyword_sys5", "sys5"),
	("mirac_token_type_keyword_sys6", "sys6"),
	("mirac_token_type_keyword_st08", "st08"),
	("mirac_token_type_keyword_st16", "st16"),
	("mirac_token_type_keyword_st32", "st32"),
	("mirac_token_type_keyword_st64", "st64"),
	("mirac_token_type_keyword_swap", "swap"),
	("mirac_token_type_keyword_u08", "u08"),
	("mirac_token_type_keyword_u16", "u16"),
	("mirac_token_type_keyword_u32", "u32"),
	("mirac_token_type_keyword_u64", "u64")
]

sorted_tokens = sorted(tokens, key=lambda x: x[1])

for token in sorted_tokens:
	print(f"{token[0]}, \"{token[1]}\",")
